<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NSI-3-IT-N138" failures="1" tests="1" name="Default test" time="5.676" errors="0" timestamp="2023-12-06T15:38:31 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.936">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your order1!] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order1!] but found [Thank you for your order!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Steps.OrderPlacing.VerifyconfirmationAndLogout(OrderPlacing.java:79)
at âœ½.Verify the Thank you for your order1!(file:///home/hemanathan.m/eclipse-workspace/Cucumber/src/test/java/Features/Orderconfirmation.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
